apiVersion: v1
kind: ConfigMap
metadata:
  labels:
  {{- include "java-app.labels" . | nindent 4 }}
  name: {{ include "java-app.fullname" . }}
data:
  {{- range $key, $value := .Values.config}}
    {{$key}}: {{tpl ($value | toString) $}}
  {{end}}
